workflows:
  build-flet-apk:
    name: Build Flet APK
    max_build_duration: 30
    environment:
      flutter: "3.22.2"
    scripts:
      - name: Install Flet
        script: |
          pip3 install flet==0.22.1
          
      - name: Build APK
        script: |
          flet build apk

      - name: Rename APK
        script: |
          APK_PATH=$(find build -name "*.apk" | head -n 1)
          cp "$APK_PATH" "./Set_Manager.apk"
          echo "✅ APK создан"

    artifacts:
      - Set_Manager.apk