workflows:
  build-flet-apk:
    name: Build Flet APK
    max_build_duration: 30
    environment:
      flutter: "3.22.2"
    scripts:
      - name: Install dependencies
        script: |
          pip3 install flet==0.22.1 requests==2.31.0 gspread==6.0.0 google-auth==2.23.4 google-api-python-client==2.108.0
          
      - name: Build APK
        script: |
          flet build apk --include-packages "requests,gspread,google.auth,googleapiclient"

      - name: Rename APK
        script: |
          APK_PATH=$(find build -name "*.apk" | head -n 1)
          cp "$APK_PATH" "./Set_Manager.apk"
          echo "✅ APK создан"

    artifacts:
      - Set_Manager.apk