workflows:
  build-flet-apk:
    name: Build Flet APK
    max_build_duration: 60
    environment:
      flutter: "3.22.2"
    scripts:
      - name: Install Flet and dependencies
        script: |
          pip3 install flet==0.22.1
          pip3 install requests==2.31.0 gspread==6.0.0 google-auth==2.23.4 google-api-python-client==2.108.0
          
      - name: Build universal APK
        script: |
          # Собираем универсальный APK со всеми архитектурами
          flet build apk --product "Set Manager"

      - name: Rename APK
        script: |
          APK_PATH=$(find build -name "*.apk" | head -n 1)
          cp "$APK_PATH" "./Set_Manager_Universal.apk"
          echo "✅ Универсальный APK создан"

    artifacts:
      - "*.apk"